plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
remote_theme: just-the-docs/just-the-docs
repository: MinecraftCommands/wiki
color_scheme: "light"
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 5
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false
  focus_shortcut_key: 'k'
enable_copy_code_button: true
exclude:
  - 404.html
nav_enabled: true
back_to_top: true
back_to_top_text: "Back to top"